### PR TITLE
Fixed the English language up a bit

### PR DESCRIPTION
**Pull request by electronicboy**
I've tried to fix the english up a little, I'm fairly sure this should be fine but you might wanna run a quick check over it.

### CODE REVIEW

**Comment by electronicboy** [comment]
there is also an issue with the plugin where bans made today are listed as being created 'tomorrow'

**Comment by alphartdev** [comment]
Hi there,
thanks for the corrections (are you pgmann on the spigot forum btw ?)

I just want to ask two questions : 
- In b4072cbefd871a81d200094e43fe4f4cd5d5b5aa , you changed "were mute" to "was muted", I understand that muted is the correct past participle of mute but I don't get why you used 'was' instead of 'were' ? Isn't 'were' the correct conjugation, or is it something common to use was instead of were ?
- In the other commit (the big one), you changed 'definitively' to 'indefinitely', I just checked in the dictionnary and you're totally right indefinitely works totally fine but I have to say that the 'in-' (which is some kind of negative prefix in English, isn't it ?) makes it a bit harder for people who don't speak a great english. I used definitely to mark the difference between a temporary and a definitive punishment and I think that the prefix 'in-' gums out the difference... Do you think it's possible to keep definitely instead of indefinitely or that it is a big mistranslation ?

Anyway again I want to thank for that great job (translating isn't that much funny) and I hope you don't mind enlighten me about my few questions.

**Comment by electronicboy** [comment]
I'm not a english professional, I just sorta use this project on a server I dev for and thought I'd pitch back to the project. Also, nope, I'm 'electronicboy' on the spigot forums, don't think I've had any interactions with this project on there other than downloading it

As for the 1st question, I did that based upon the current concept that you are muted right now, I may have goof'd in understanding when that was sent to the player, I thought it was sent when they received the mute? But, I was a bit tired this morning, so I may have goofed. But, if my tired reading was correct, it's based upon the fact that it's more common to say it like that. One thing you'll learn is that english has a ton of rules as for how stuff to be formatted and all that, but more than often you'll find that all of the rules have exceptions in.

As for the indefinitely, I feel that 'indefinitely' is sorta more accurate in the fact that it's a time quantity we're trying to fill, 'definitively' isn't a word that we use often other than in extremely formal cases and is more described to state that the decision made is final. if indefinitely is likely to cause confusion, I'd consider using 'permanently' instead as it more fits the terms that we use on servers as well as satisfied the fact that we're trying to specify a time-period of the action.

**Comment by alphartdev** [comment]
Yeah I definitely think that permanently is easier, so I just added it.
Anyway thanks for your help, that's really appreciated :)
P.S: I didn't forget your webinterface PR, I just need to test it.

**Pull request merged**
