### PR TITLE
Update messages_en.language

### PR DESCRIPTION
**Pull request by JamesJ99**
Corrected a few grammatical mistakes. (Sigh...)

### CODE REVIEW

**Comment by electronicboy** [comment]
The way you wrote your commit comment sounds a little rude, not everybody's first language is English.

Also, I'm not sure your language fixes will be applicable in the real world, I think that 'for the reason', would be better as, just simply 'for'. Most people use reasons as simple as 'grief' or 'advertising'. The existing text fits how most people format their ban messages, if you wanted it to be more professional replacing the 'reason:' with 'for' would probably be more accurate in terms of keeping the professionalism with standard ban message reasons.

**Comment by JamesJ99** [comment]
I think that if you read the file, it says at the top "Thanks to JamesJ", I was fixing my own grammatical errors...

**Comment by JamesJ99** [comment]
Which Is why I added the "(Sigh...)" because I had fixed the translations, but missed those... Which was incredibly stupid of me.

**Comment by electronicboy** [comment]
Oh, sorry, I hadn't looked at the whole file, and dealing with a poor internet connection sorta makes you faster to react before it drops again!

Either way, my comment still stands, I think that replacing the 'reason:' with 'for' would suffice a lot more in real-world practice, I know every server I've ever been on uses messages which would be more fitting of 'for' than 'for the reason', unless you was to go 'for the reason:' (noting the : ), however I think thats a bit over-kill and just doesn't sound as it would fit properly in most cases.

**Comment by JamesJ99** [comment]
If you wish to change it, please do so. That was just how I interpreted it, however, that may not be how everyone else does.

**Comment by alphartdev** [comment]
Whereas I agree with you @JamesJ99 because I always want something that is as clear as possible, I also like when messages aren't too large (minecraft chat is so small :'(). I think you were right to change the basic : "Reason:" to something more literary like "for the reason" or simply "for". So if you both think a simple "for" is understandable (?) I would use that so we merge the best of your ideas :)

**Pull request closed without merging**
