### PR TITLE
Add bypass bungee check in config for Waterfall support

### PR DESCRIPTION
**Pull request by xxroltsxx**
Add bypass bungee check for waterfall support: https://github.com/WaterfallMC/Waterfall

### CODE REVIEW

**Comment by Techcable** [comment]
Itd be neat if it automatically detected waterfall.
Check if 
`ProxyServer.getInstance().getName().equals("BungeeCord")`
and disable the check automatically if not :)

**Comment by SmallSansSerif** [comment]
@xxroltsxx do you have a .jar build of this anywhere? I would like to try out Waterfall but have BAT as well.

**Comment by minecrafter** [comment]
@SmallSansSerif https://getwaterfall.xyz/builds/latest

**Comment by SmallSansSerif** [comment]
@minecrafter Thanks but I was looking for the updated BAT jar.

**Comment by xxroltsxx** [comment]
https://owncloud.rolts.me/index.php/s/zZqclSHJqdADuLT @SmallSansSerif

**Comment by xxroltsxx** [comment]
There you go @Techcable Thanks for the suggestion.

**Comment by alphartdev** [comment]
Maked it a bit less specific, so it supports all forks (using name != "BungeeCord" rather than name=="Waterfall" as Techcable pointed out)

**Comment by 7h3ev1l** [comment]
`12:21:51 [SEVERE] [BungeeAdminTools] Your BungeeCord build (#127) is not supported. Please use at least BungeeCord #878
12:21:51 [SEVERE] [BungeeAdminTools] BAT is going to shutdown ...`

  I just downloaded latest waterfall and bat.

**Comment by xxroltsxx** [comment]
Where?

**Pull request merged**
